### ISSUE TITLE
Error running ranking and trading client : TypeError: model_schema() got an unexpected keyword argument 'generic_origin'

### ISSUE THREAD

**Issue by sukhcs** [yeonholee50/AmpyFin#14]
Getting an error when running ranking_client and trading_client. I am on Python 3.11.10.

>python ranking_client.py
Traceback (most recent call last):
  File "\AmpyFin\ranking_client.py", line 12, in <module>
    from alpaca.trading.client import TradingClient
  File "\anaconda3\envs\ampyfin\Lib\site-packages\alpaca\trading\__init__.py", line 1, in <module>
    from alpaca.trading.client import *
  File "\anaconda3\envs\ampyfin\Lib\site-packages\alpaca\trading\client.py", line 5, in <module>
    from alpaca.common import RawData
  File "\anaconda3\envs\ampyfin\Lib\site-packages\alpaca\common\__init__.py", line 1, in <module>
    from alpaca.common.models import *
  File "\anaconda3\envs\ampyfin\Lib\site-packages\alpaca\common\models.py", line 6, in <module>
    class ValidateBaseModel(BaseModel, validate_assignment=True):
  File "\anaconda3\envs\ampyfin\Lib\site-packages\pydantic\_internal\_model_construction.py", line 226, in __new__
    complete_model_class(
  File "\anaconda3\envs\ampyfin\Lib\site-packages\pydantic\_internal\_model_construction.py", line 658, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\anaconda3\envs\ampyfin\Lib\site-packages\pydantic\main.py", line 702, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "\anaconda3\envs\ampyfin\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 84, in __call__       
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\anaconda3\envs\ampyfin\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 612, in generate_schema        
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\anaconda3\envs\ampyfin\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 881, in _generate_schema_inner 
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "\anaconda3\envs\ampyfin\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 707, in _model_schema
    model_schema = core_schema.model_schema(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: model_schema() got an unexpected keyword argument 'generic_origin'

**Comment by yeonholee50** [comment]
There seems to be a compatability issue with the current version of Python with pydantic. You may need to downgrade your Python version and then retry. I will look into this seperately

**Comment by sukhcs** [comment]
Thanks, I tried Python 3.10 and it works now.
