### ISSUE TITLE
The trading_client and ranking_client fails at rank_collection.find_one with unsubscriptable NoneType object. 

### ISSUE THREAD

**Issue by sukhcs** [yeonholee50/AmpyFin#16]
% python trading_client.py 
2024-12-05 11:55:24 - INFO - Market is open. Waiting for 60 seconds.
2024-12-05 11:55:24 - INFO - Calling NASDAQ 100 to retrieve tickers.
2024-12-05 11:55:24 - INFO - Successfully retrieved NASDAQ 100 tickers.
2024-12-05 11:55:25 - INFO - Successfully inserted NASDAQ 100 tickers into MongoDB.
2024-12-05 11:55:25 - INFO - MongoDB connection closed.
Traceback (most recent call last):
  File "AmpyFin/trading_client.py", line 230, in <module>
    main()
  File "AmpyFin/trading_client.py", line 111, in main
    rank = rank_collection.find_one({'strategy': strategy.__name__})['rank']
TypeError: 'NoneType' object is not subscriptable

**Comment by sukhcs** [comment]
Even though the trading_client has a connection with mongodb and is able to load ndaq100_stickers but it fails to create a collection for market_status in mongodb. Need more error handling around external api calls.

**Comment by sukhcs** [comment]
This was solved by creating a "market_status" collection in mongodb. I'll send a pull request for creating this collection at the setup time. @yeonholee50

**Comment by yeonholee50** [comment]
Just finished updating market status initialization in mongo_setup.py script in helper folder. Thank you for pointing this out. Please take a look and if you approve, close the issue. Otherwise, please lmk. Thanks!!!
