### ISSUE TITLE
ranking_client.py and trading_client.py error

### ISSUE THREAD

**Issue by henmel1** [yeonholee50/AmpyFin#4]
When running python ranking_client.py and python trading_client.py in separate terminal windows as described in the README, after I have my config.py file filled out properly, I get the following errors:

ranking_client.py:
`Traceback (most recent call last):
  File "/home/henry/AmpyFin/ranking_client.py", line 455, in <module>
    main()
  File "/home/henry/AmpyFin/ranking_client.py", line 374, in main
    status = mongo_client.market_data.market_status.find_one({})["market_status"]
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/collection.py", line 1709, in find_one
    for result in cursor.limit(-1):
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1281, in __next__
    return self.next()
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1257, in next
    if len(self._data) or self._refresh():
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1205, in _refresh
    self._send_message(q)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1100, in _send_message
    response = client._run_operation(
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/_csot.py", line 120, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1754, in _run_operation
    return self._retryable_read(
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1863, in _retryable_read
    return self._retry_internal(
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/_csot.py", line 120, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1830, in _retry_internal
    ).run()
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2554, in run
    return self._read() if self._is_read else self._write()
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2691, in _read
    with self._client._conn_from_server(self._read_pref, self._server, self._session) as (
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1683, in _conn_from_server
    with self._checkout(server, session) as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1593, in _checkout
    with server.checkout(handler=err_handler) as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/pool.py", line 1336, in checkout
    conn = self._get_conn(checkout_started_time, handler=handler)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/pool.py", line 1495, in _get_conn
    conn = self.connect(handler=handler)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/pool.py", line 1296, in connect
    conn.authenticate()
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/pool.py", line 648, in authenticate
    auth.authenticate(creds, self, reauthenticate=reauthenticate)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/auth.py", line 452, in authenticate
    auth_func(credentials, conn)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/auth.py", line 356, in _authenticate_default
    return _authenticate_scram(credentials, conn, "SCRAM-SHA-1")
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/auth.py", line 95, in _authenticate_scram
    res = conn.command(source, cmd)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/helpers.py", line 45, in inner
    return func(*args, **kwargs)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/pool.py", line 538, in command
    return command(
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/network.py", line 218, in command
    helpers_shared._check_command_response(
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/helpers_shared.py", line 247, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: bad auth : Authentication failed., full error: {'ok': 0, 'errmsg': 'bad auth : Authentication failed.', 'code': 8000, 'codeName': 'AtlasError'}
`

trading_client.py:
`  File "/home/henry/AmpyFin/trading_client.py", line 230, in <module>
    main()
  File "/home/henry/AmpyFin/trading_client.py", line 100, in main
    market_collection.update_one({}, {"$set": {"market_status": status}})
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/collection.py", line 1291, in update_one
    self._update_retryable(
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/collection.py", line 1086, in _update_retryable
    return self._database.client._retryable_write(
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1898, in _retryable_write
    return self._retry_with_session(retryable, func, s, bulk, operation, operation_id)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1784, in _retry_with_session
    return self._retry_internal(
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/_csot.py", line 120, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1830, in _retry_internal
    ).run()
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2554, in run
    return self._read() if self._is_read else self._write()
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2663, in _write
    with self._client._checkout(self._server, self._session) as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1593, in _checkout
    with server.checkout(handler=err_handler) as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/pool.py", line 1336, in checkout
    conn = self._get_conn(checkout_started_time, handler=handler)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/pool.py", line 1495, in _get_conn
    conn = self.connect(handler=handler)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/pool.py", line 1296, in connect
    conn.authenticate()
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/pool.py", line 648, in authenticate
    auth.authenticate(creds, self, reauthenticate=reauthenticate)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/auth.py", line 452, in authenticate
    auth_func(credentials, conn)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/auth.py", line 356, in _authenticate_default
    return _authenticate_scram(credentials, conn, "SCRAM-SHA-1")
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/auth.py", line 95, in _authenticate_scram
    res = conn.command(source, cmd)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/helpers.py", line 45, in inner
    return func(*args, **kwargs)
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/pool.py", line 538, in command
    return command(
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/synchronous/network.py", line 218, in command
    helpers_shared._check_command_response(
  File "/home/henry/.local/lib/python3.10/site-packages/pymongo/helpers_shared.py", line 247, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: bad auth : Authentication failed., full error: {'ok': 0, 'errmsg': 'bad auth : Authentication failed.', 'code': 8000, 'codeName': 'AtlasError'}`

Please help! AmpyFin sounds really cool and I would like to test it out.

**Comment by yeonholee50** [comment]
https://stackoverflow.com/questions/60020381/mongodb-atlas-bad-auth-authentication-failed-code-8000

Please make sure you are using your mongodb link - not mine. These mongo_url are in both trading_client.py and ranking_client.py - I should document these on README.md probably to help with set up. I probably have a different cluster value than yours in my url. Also make sure to give yourself ip access to your database or just give access to 0.0.0.0/0 for testing purposes. Please let me know if the issue persists. I will be continuing to monitor this issue.

**Comment by Morritse** [comment]
For quick testing try 
```
from pymongo import MongoClient
from config import MONGO_DB_USER, MONGO_DB_PASS

mongo_url = f"mongodb+srv://{MONGO_DB_USER}:{MONGO_DB_PASS}@cluster0.tlesn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
client = MongoClient(mongo_url)
try:
    # The ismaster command is cheap and does not require auth
    client.admin.command('ismaster')
    print("MongoDB connection successful!")
except Exception as e:
    print(f"MongoDB connection failed: {str(e)}")
```

**Comment by yeonholee50** [comment]
I would do git pull now. Set up instruction is now much clearer and the packages are correctly in place. Please lmk if the issue persists
